/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import SearchBar from "./SearchBar";
import MainContent from "./MainContent";
import Footer from "./Footer";

const DoctorPage = () => {
  return (
    <div className="flex overflow-hidden flex-col pb-24 bg-slate-50">
      <Header />
      <SearchBar />
      <MainContent />
      <Footer />
    </div>
  );
};

export default DoctorPage;
