/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { Link } from "react-router-dom";

const Header = () => {
  return (
    <header className="flex overflow-hidden flex-wrap gap-5 justify-between items-center px-20 py-4 w-full bg-white border-b border-slate-300 shadow-[0px_10px_24px_rgba(172,172,172,0.15)] max-md:px-5 max-md:max-w-full">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/d52bb1fe9d8e00522f902f7cb874aa61238c031e0222432be335b62ecadb363a?placeholderIfAbsent=true&apiKey=4c137795ca7946528ace3d8e35f13cac"
        alt="Company Logo"
        className="object-contain shrink-0 self-stretch my-auto max-w-full aspect-[4.35] w-[135px]"
      />
      <nav className="flex flex-wrap gap-10 items-start self-stretch my-auto text-base font-medium leading-loose text-slate-800 max-md:max-w-full">
        <Link to="/find-doctor">Find Doctor</Link>
        <Link to="/about">About</Link>
        <div className="flex gap-1 items-start">
          <Link to="/for-corporates">For Corporates</Link>
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/ac5e652274b6a266226403431c35e293fb2d4844c0bcf04397e5397343ff1630?placeholderIfAbsent=true&apiKey=4c137795ca7946528ace3d8e35f13cac"
            alt=""
            className="object-contain shrink-0 w-6 aspect-square"
          />
        </div>
        <div className="flex gap-1 items-start">
          <Link to="/for-providers">For Providers</Link>
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/ac5e652274b6a266226403431c35e293fb2d4844c0bcf04397e5397343ff1630?placeholderIfAbsent=true&apiKey=4c137795ca7946528ace3d8e35f13cac"
            alt=""
            className="object-contain shrink-0 w-6 aspect-square"
          />
        </div>
      </nav>
      <div className="flex gap-3 items-start self-stretch text-base font-semibold leading-loose">
        <Link
          to="/signin"
          className="gap-2.5 self-stretch px-5 py-2 text-blue-600 rounded-md border border-blue-600 border-solid"
        >
          Sign In
        </Link>
        <Link
          to="/register"
          className="gap-2.5 self-stretch px-5 py-2 text-white whitespace-nowrap bg-blue-600 rounded-md"
        >
          Register
        </Link>
      </div>
    </header>
  );
};

export default Header;
