// /**
//  * This code was generated by Builder.io.
//  */
// import React from "react";

// const LocationCard = ({ name, price, address, isOpen, hours }) => {
//   return (
//     <div className="flex overflow-hidden flex-wrap gap-5 justify-between px-9 py-6 mt-8 bg-white rounded-xl border border-solid border-blue-600 border-opacity-50 max-md:px-5 max-md:max-w-full">
//       <div className="flex flex-col items-start text-xs">
//         <div className="flex gap-2.5 self-stretch text-lg font-semibold text-blue-600">
//           <img
//             loading="lazy"
//             src="/DoctorProfile/LocationIcon.png"
//             alt=""
//             className="object-contain shrink-0 aspect-[0.95] w-[19px]"
//           />
//           <div className="grow shrink my-auto w-[297px]">{name}</div>
//         </div>
//         <div className="flex gap-1.5 mt-2">
//           <div className="font-semibold text-slate-800">{price}</div>
//           <div className="font-medium text-gray-400 basis-auto">
//             (For Video Consultation)
//           </div>
//         </div>
//         <div className="flex gap-3.5 mt-8 font-medium">
//           <img
//             loading="lazy"
//             src="/DoctorProfile/Locationbig.png"
//             alt=""
//             className="object-contain shrink-0 rounded-2xl aspect-[0.98] w-[59px]"
//           />
//           <div className="flex flex-row items-start">
//             <div className="self-stretch text-slate-800 w-[140px] py-4">{address}</div>
//             <div className="">
//               <button className="flex gap-2 mt-4 text-[#FF7F50]">
//                 <img
//                   loading="lazy"
//                   src="/DoctorProfile/phone.png"
//                   alt=""
//                   className="object-contain shrink-0 self-start w-3.5 aspect-square"
//                 />
//                 <span>Call Now</span>
//               </button>
//               <button className="flex gap-2 mt-2 text-[#FF7F50]">
//                 <img
//                   loading="lazy"
//                   src="/DoctorProfile/direction.png"
//                   alt=""
//                   className="object-contain shrink-0 w-3.5 aspect-square"
//                 />
//                 <span>Get Direction</span>
//               </button>
//             </div>
//           </div>
//         </div>
//       </div>
//       <div className="flex flex-col">
//         <div className="flex gap-5 justify-between">
      
//           <div className="flex gap-3 self-start text-sm text-slate-400">
           
//           </div>
//         </div>
//         <a
//           href="#"
//           className="gap-2.5 self-end px-5 py-1 mt-20 text-base font-medium leading-loose text-white bg-blue-600 rounded-md min-h-[42px] max-md:mt-10 h-[40px]"
//         >
//           Visit website
//         </a>
//       </div>
//     </div>
//   );
// };

// export default LocationCard;
