/**
 * This code was generated by Builder.io.
 */
import React from "react";

const ArticleCard = (
  { image, category, date, title, readTime, content }) => {
  return (
    <div className="flex flex-col w-[330px] border border-solid bg-white bg-opacity-10 border-blue-950">
      <img
        loading="lazy"
        src={image}
        alt={title}
        className="object-contain w-full aspect-square max-md:mt-8"
      />
      <div className="flex flex-col items-start py-4 pr-2 pl-4 mx-auto w-full rounded-none  max-md:mt-8">
        <div className="flex gap-2.5">
          <div className="flex flex-col text-xs font-medium">
            <div className="text-blue-600">{category}</div>
            <div className="self-start mt-2.5 text-xs text-neutral-500">
              {date}
            </div>
            <div className="mt-2.5 text-slate-800">{title}</div>
          </div>
          <div className="my-auto text-xs text-neutral-500">{readTime}</div>
        </div>
        <p className="self-stretch mt-1.5 text-xs leading-4 text-neutral-800 text-opacity-70">
          {content}
        </p>
        <button className="gap-2.5 self-stretch px-4 py-px mt-4 text-xs font-medium leading-6 text-white bg-blue-600 rounded-md min-h-[26px]">
          Learn more
        </button>
      </div>
    </div>
  );
};

export default ArticleCard;
